
version: '3'

services:
  hue-latest:
      image: gethue/hue:latest
      hostname: hue
      container_name: hue
      dns: 8.8.8.8
      ports:
        - "8888:8888"
      volumes:
        - ./desktop/conf/hue.ini:/usr/share/hue/desktop/conf/z-hue.ini
      depends_on:
        - "mysql-hue"

  mysql-hue:
      image: mysql:latest
      ports:
          - "3306:3306"
      volumes:
          - data:/var/lib/mysql
          - ./init.sql:/data/application/init.sql
      command: --init-file /data/application/init.sql
      environment:
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: hue
          MYSQL_USER: root
          MYSQL_PASSWORD: root
volumes:
  data:
